# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: vs2017-win2016

steps:
- task: SSISDeploy@1
  inputs:
    sourcePath: '"C:\Users\v-lfreitas\source\repos\Luís Testing\Luís Testing\bin\Development\Luís Testing.ispac"'
    destinationType: 'ssisdb'
    destinationServer: 'WINDOWS-VSCF65A'
    destinationPath: '/SSISDB/410/[Luís Testing]'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'yes'
