# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  #vmImage: Default
  name: default
  
steps:
- task: SSISDeploy@1
  displayName: 'Deploy APP'
  inputs:
    sourcePath: '""C:\Users\v-lfreitas\OneDrive - Microsoft\Cases Files\Suhas\Ispac\APP.ispac""'
    destinationType: 'ssisdb'
    destinationServer: 'WINDOWS-VSCF65A'
    destinationPath: '/SSISDB/DDFO'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'

- task: SSISDeploy@1
  inputs:
    sourcePath: 'C:\Users\v-lfreitas\OneDrive - Microsoft\Cases Files\Suhas\Ispac\Feed_ETL.ispac'
    destinationType: 'ssisdb'
    destinationServer: 'WINDOWS-VSCF65A'
    destinationPath: '/SSISDB/DDFO'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'


- task: SSISDeploy@1
  displayName: 'Deploy Reference_ETL'
  inputs:
    sourcePath: '""C:\Users\v-lfreitas\OneDrive - Microsoft\Cases Files\Suhas\Ispac\Reference_ETL.ispac""'
    destinationType: 'ssisdb'
    destinationServer: 'WINDOWS-VSCF65A'
    destinationPath: '/SSISDB/DDFO'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'


- task: SSISCatalog@0
  displayName: 'SSISDB Config'
  inputs:
    configSource: 'filePath'
    configPath: '""C:\Users\v-lfreitas\OneDrive - Microsoft\Cases Files\Suhas\Ispac\configure_ssis_catalog.json""'
    rollBackOnError: true
    targetServer: 'WINDOWS-VSCF65A'
    authType: 'win'